# Generated by Django 5.0.4 on 2024-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('user_is_deleted', models.BooleanField(default=False)),
                ('user_created_date', models.DateTimeField(auto_now_add=True)),
                ('user_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
