# Generated by Django 5.0.4 on 2024-05-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='applicationuser',
            old_name='user_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='applicationuser',
            old_name='user_is_deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='applicationuser',
            old_name='user_updated_date',
            new_name='updated_date',
        ),
    ]
