# Generated by Django 5.0.4 on 2024-05-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_user', '0002_alter_applicationuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationuser',
            old_name='user_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='applicationuser',
            old_name='user_password',
            new_name='username',
        ),
    ]
