# Generated by Django 5.0.4 on 2024-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('resolved_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
